export default {
  login: "bootstrap",
  id: 788835,
  node_id: "MDQ6VXNlcjc4ODgzNQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/788835?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bootstrap",
  html_url: "https://github.com/bootstrap",
  followers_url: "https://api.github.com/users/bootstrap/followers",
  following_url:
    "https://api.github.com/users/bootstrap/following{/other_user}",
  gists_url: "https://api.github.com/users/bootstrap/gists{/gist_id}",
  starred_url: "https://api.github.com/users/bootstrap/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bootstrap/subscriptions",
  organizations_url: "https://api.github.com/users/bootstrap/orgs",
  repos_url: "https://api.github.com/users/bootstrap/repos",
  events_url: "https://api.github.com/users/bootstrap/events{/privacy}",
  received_events_url: "https://api.github.com/users/bootstrap/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 137,
  public_gists: 0,
  followers: 164,
  following: 5,
  created_at: "2011-05-15T07:02:40Z",
  updated_at: "2021-10-11T15:53:15Z",
};
